
# About the project

__Introduction to Open Data Science 2019__. A fast track on the basis of data science with an open data tools approach. 

I was very lucky to see an email only a day apart from the last day to sing up for the course while cleaning up my inbox with over 300 messages - mostly junk. I got very interested right away and have not been this exited to learn new tools for many years.

I have some experience with R long ago and have just startetd this year to learn coding properly, but must say it has been quite difficult due to the fast proceeding paste in Savonia Code Academy help in Kuopio. The studies are taking a lot of time, but I trust myself to get more into data science along the way.  So far I installed all necessary tools from scrach today --_actually tomorrow already_-- and did the R introductions, as well as an extra did a small course available on open data and science. I can well adobt to the ideas in this course and have actually published only on open access journals.

Very optimistic about the course and feel __lucky__ to join. 

[My IODS-project](https://github.com/ottomykkanen/IODS-project)

[My diary web page](https://ottomykkanen.github.io/IODS-project/index.html)


### Course related basic information sites

- [R project org](https://www.r-project.org/)
- [RStudio](http://www.rstudio.com/ide/)
- [GitHub](https://github.com/)

### Cheat Sheets and books

- [Course Book - IODS course](https://mooc.helsinki.fi/pluginfile.php/78192/course/section/3817/MABS4IODS.pdf)

- [Statistical Analysis with R - for Dummies](http://library.sadjad.ac.ir/opac//temp/19241.pdf)

- [RStudio related Cheat Sheets](https://rstudio.com/resources/cheatsheets/)

- [CHANGING THE COURSE: FROM BORING NUMERACY TO INSPIRING: LITERACY](https://iase-web.org/icots/9/proceedings/pdfs/ICOTS9_7D2_VEHKALAHTI.pdf?1405041696) *course historical*

### R Info

__*Data Explorations*__

- __head()__ *displays the first 6 rows by default*
- __dim()__ *displays the type and a preview of all columns as a row*
- __glimpse()__ *display a vertical preview of the datase (pkg dplyr)*
- __summary()__ *displays data type and attributes which are especially useful for numeric attributes*
- __skim()__ *good addition to the summary function (pkg skimr)*
- __DataExplorer__ *fast track exploration try out using line "DataExplorer::create_report() works better in R cause issues with pandoc??*

__*Most used pakages*__

- library(psych)
- library(pastecs)
- library(tidyr)
- library(dplyr)
- library(GGally)
- library(ggpubr)
- library(ggplot2)
- library(skimr)
- library(DataExplorer)

***

