---
title: "IODS course project"
author: "Rong Guang"
output:
  html_document:
    fig_caption: yes
    theme: flatly
    highlight: haddock
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_section: no
  pdf_document:
    toc: yes
    toc_depth: '3'
bibliography: citations.bib
---

***

# Introduction to Open Data Science - Course Project

```{r child = "chapter1.Rmd"}
# This will include Chapter 1 (that is updated in its own file) in the document.
```
  

***
  
```{r child = "chapter2.Rmd", warning = F, message = F}
# This will include Chapter 2 (that is updated in its own file) in the document.
```

***

```{r child = "chapter3.Rmd", warning = F, message = F}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

***


```{r child = "chapter4.Rmd", warning = F, message = F}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

***

```{r child = "chapter5.Rmd", warning = F, message = F}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

***

```{r child = "chapter6.Rmd", warning = F, message = F}
# This will include Chapter 6 (that is updated in its own file) in the document.
```

***